---
name: Bug Report
description: Report a bug
title: ' '
labels: bug
body:
  - type: dropdown
    id: version
    attributes:
      label: Bashly Version
      description: What version of bashly are you running?
      options:
        - Latest Ruby Gem
        - Latest Docker Image
        - Edge Ruby Gem
        - Edge Docker Image
        - Older Ruby Gem
        - Older Docker Image
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Describe the bug.
    validations:
      required: true
  
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction Steps
      description: Provide the minimal set of steps required to reproduce the bug, including a `bashly.yml` if relevant.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What happened?

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect would happen?
