name: Test
on:
  pull_request:
  push:

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    env:
      BRANCH_NAME: ${{ github.head_ref || github.ref_name }} 
    - name: Echo
      run: echo "$BRANCH_NAME"
