# name: Test
# on:
#   pull_request:
#   push:

# jobs:
#   test:
#     name: ZSH Test

#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v4

#     - name: Install zsh
#       run: sudo apt install -y zsh

#     - name: Start TMate session
#       uses: mxschmitt/action-tmate@v3
