name: Test
on:
  pull_request:
  push: { branches: master }

jobs:
  test:
    name: Ruby ${{ matrix.ruby }}
    runs-on: ubuntu-latest
    strategy:
      matrix: { ruby: ['2.5', '3.0'] }

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with: 
        ruby-version: '${{ matrix.ruby }}'
        bundler-cache: true

    - name: Update system
      run: sudo apt update -y && sudo apt upgrade -y && sudo apt autoremove -y

    - name: Run tests
      run: ruby test.rb

    # The below uses docker to perform the same tests

    # - name: Build docker images
    #   run: docker-compose build

    # - name: Test ruby 2
    #   run: docker-compose run ruby2

    # - name: Test ruby 3
    #   run: docker-compose run ruby3
